# Generated by Django 5.1.3 on 2024-11-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('group_description', models.TextField(verbose_name='Описание группы')),
                ('direction', models.CharField(choices=[('FRONTEND', 'Фронтенд'), ('BACKEND', 'Бекенд')], max_length=10, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Телефонный номер')),
                ('telegram', models.CharField(max_length=100, unique=True, verbose_name='Telegram')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Фото')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
